
server:
  port: 18082
 
mybatis:
  type-aliases-package: com.example.resource.model

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

security:
  oauth2:
    client:
      client-id: resource-server
      client-secret: demo
    resource:
      token-info-uri: http://localhost:18081/authz/oauth/check_token
#      jwt:
#        key-uri: http://localhost:18081/authz/oauth/token_key

