server:
  port: 18081
  servlet:
    context-path: /authz

mybatis:
  type-aliases-package: com.example.authz.model
  

spring:
  datasource:
    platform: h2
  h2:
    console:
      enabled: true
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp