server:
  port: 18081
  servlet:
    context-path: /authz

mybatis:
  type-aliases-package: com.example.authz.model
  
spring:
  datasource:
    platform: h2
#    url: jdbc:mysql://localhost:3306/testdb
#    username: user
#    password: password
#    driver-class-name: com.mysql.jdbc.Driver
#    platform: mysql
  

#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp